version: '3.8'

services:
  hotkey-worker:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile-hotkey-worker
    environment:
      - etcdServer=http://etcd:2379
      - SERVER_PORT=8111
      - localAddress=
    networks:
      - code2offer-net
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    restart: always

# 💡 这部分绝对不能少！
networks:
  code2offer-net:
    external: true